### ISSUE TITLE
what material are these flowers made of?

### ISSUE THREAD

**Issue by LuckyFishGeek** [taunoe/tauno-env-monitor#6]
awesome
Hope to provide a tutorial on how to make flower
![Snipaste_2022-06-20_08-32-19](https://user-images.githubusercontent.com/29472751/174506584-6e0b8d86-f6ee-44c7-91e8-dae97162ccef.png)
s

**Comment by taunoe** [comment]
This is regular bare copper wire. Without enamel. I use round pliers. Something like that:
![Ekraanipilt 2022-06-20 20-58-09](https://user-images.githubusercontent.com/1520326/174656644-ad55f01f-43fb-4ecb-b755-3476e8ee8dd5.jpg)

**Comment by LuckyFishGeek** [comment]
> This is regular bare copper wire. Without enamel. I use round pliers. Something like that: ![Ekraanipilt 2022-06-20 20-58-09](https://user-images.githubusercontent.com/1520326/174656644-ad55f01f-43fb-4ecb-b755-3476e8ee8dd5.jpg)

Thank you for your kind reply Very nice work
 Again, I'm asking for your help. What did you use to hold these flowers in place?

**Comment by taunoe** [comment]
Some parts are drilled into wood and others are glued (super glue).

**Comment by LuckyFishGeek** [comment]
@taunoe  Thank you for your kind help, I will follow the tutorial you provided to learn how to make!
very good work
